plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true

      languages:
        - locale: en
          default: true
          name: English
          build: true

        - locale: ja
          name: 日本語
          build: true

          nav_translations:
            Home: ホーム
            Guidelines: ガイドライン
            Our next steps: 今後の取り組み
            Download: ダウンロード
            News & Updates: ニュース・更新情報
            Working group: ワーキンググループ
            How to contribute: 貢献するには
            How to cite: 引用方法

  - offline

  - search:
      lang:
        - en
        - ja

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
